#!/bin/bash

VERSION=1.6.1
STORAGE_SERVER_PORT=8087
STORAGE_SERVER_DATA_BUCKET=oicr.icgc.test
STORAGE_SERVER_STATE_BUCKET=oicr.icgc.test
STORAGE_SERVER_OBJECT_SENTINEL=heliograph
STORAGE_SERVER_DATA_DIR=data
SERVER_URL=http://localhost:8080
OBJECT_STORAGE_ACCESS_KEY=minio
OBJECT_STORAGE_SECRET_KEY=minio123
OBJECT_STORAGE_URL=http://localhost:8085
AUTH_SERVER_URL=http://localhost:8084/check_token/
AUTH_SERVER_CLIENTID=3kJhz9pNtC0pFHAxr2SPkUkGjXrkWWqGcnPC0vBP
AUTH_SERVER_CLIENTSECRET=v9mjRtuEVwpt7cgqnsq6mxtCa5FbUOpKLGh7WX8a1dWbBKfrM3iV3VYMtE60jr3W7GLWtNeYIaJ8EUxPkaInclWVXf64qKdR3IKwyfpDU7JhvWEwIYQYdwV1YAUZjB2e
UPLOAD_SCOPE=collab.upload
DOWNLOAD_SCOPE=collab.download

docker run  \
    --rm  \
    --log-driver json-file \
    --detach \
    --network host \
    --name score-server-$VERSION \
	-e STORAGE_SERVER_PORT=$STORAGE_SERVER_PORT \
	-e STORAGE_SERVER_DATA_BUCKET=$STORAGE_SERVER_DATA_BUCKET \
	-e STORAGE_SERVER_STATE_BUCKET=$STORAGE_SERVER_STATE_BUCKET \
	-e STORAGE_SERVER_OBJECT_SENTINEL=$STORAGE_SERVER_OBJECT_SENTINEL \
	-e STORAGE_SERVER_DATA_DIR=$STORAGE_SERVER_DATA_DIR \
	-e SERVER_URL=$SERVER_URL \
	-e OBJECT_STORAGE_ACCESS_KEY=$OBJECT_STORAGE_ACCESS_KEY \
	-e OBJECT_STORAGE_SECRET_KEY=$OBJECT_STORAGE_SECRET_KEY \
	-e OBJECT_STORAGE_URL=$OBJECT_STORAGE_URL \
	-e AUTH_SERVER_URL=$AUTH_SERVER_URL \
	-e AUTH_SERVER_CLIENTID=$AUTH_SERVER_CLIENTID \
	-e AUTH_SERVER_CLIENTSECRET=$AUTH_SERVER_CLIENTSECRET \
	-e UPLOAD_SCOPE=$UPLOAD_SCOPE \
	-e DOWNLOAD_SCOPE=$DOWNLOAD_SCOPE \
    overture/score-server:$VERSION

