#!/bin/bash

BASH_SCRIPT=`readlink -f ${BASH_SOURCE[0]}`
BASH_SCRIPT_DIR=$( dirname  "${BASH_SCRIPT}")

DOCKERFILE_NAME=Dockerfile.dev \
	docker-compose \
	-f ${BASH_SCRIPT_DIR}/../../docker-compose.yml \
	run --rm score-client score-client $@
