#
# Copyright (c) 2016 The Ontario Institute for Cancer Research. All rights reserved.
#
# This program and the accompanying materials are made available under the terms of the GNU Public License v3.0.
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
# SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
# IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# DCC Storage Server - Configuration
#

###############################################################################
# Profile - common
###############################################################################

server:
  port: 5431
  compression:
    enabled: true
    mime-types: application/json
  #allowedOrigins can be configured to contain multiple values, all separated by commas
  cors:
    allowedOrigins: http://localhost:8081
s3:
  secured: false #true
  sigV4Enabled: true

  #amazon
  endpoint: https://object.cancercollaboratory.org:9080 #s3-external-1.amazonaws.com

  # an optional override to replace the s3 endpoint, useful to proxy requests
  preSignedUrl:
    override:
      host:

metadata:
  useLegacyMode: false

bucket:
  name.object: score-submission-rdpc-collab-qa #score-rdpc-collab-qa #icgc-argo-collab #oicr.icgc
  name.state: score-submission-rdpc-collab-qa.state #score-rdpc-collab-qa.state #icgc-argo-collab.state #oicr.icgc
  size.pool: 0
  size.key: 2

object:
  sentinel: heliograph

collaboratory:
  upload.directory: upload
  upload.expiration: 6
  data.directory: data

  # COL-131: Change pre-signed URLs TTL to 1 day max
  download.expiration: 1

upload:
  retry.limit: 5
  partsize: 1073741824 #20000000
  connection.timeout: 15000

  # Every day at midnight
  clean.cron: "0 0 0 * * ?"
  clean.enabled: true

auth:
  # Connection retries in case of connection failure
  connection:
    # Max number of retries
    maxRetries: 5

    # Initial timeoutMs before the first retry. In milliseconds.
    initialBackoff: 15000

    # Multiplier that defines value of consequent timeouts before the next retry.
    # E.g. TIMEOUT(n) = TIMEOUT(n-1) * MULTIPLIER
    multiplier: 2.0

#allowedOrigins can be configured to contain multiple values, all separated by commas
management:
  endpoints:
    web:
      cors:
        allowedOrigins: http://localhost:8081

---

###############################################################################
# Profile - "ssl"
# this is the configuration for the service using the self-signed cert created
# for initial production deployments. key-store-password would still need to
# be specified in the properties file
###############################################################################

spring.profiles: ssl

# Server
server:
  ssl:
    key-store-type: JKS
    key-store: src/main/cert/service.jks
    key-alias: object-store-service

---

###############################################################################
# Profile - "amazon"
###############################################################################

spring:
  profiles: amazon
  profiles.include: prod

s3:
  endpoint: https://object.cancercollaboratory.org:9080 #s3-external-1.amazonaws.com
  masterEncryptionKeyId: af628f04-ac12-4b11-bf83-6545fd44ad18

bucket:
  name.object: score-submission-rdpc-collab-qa #score-rdpc-collab-qa #icgc-argo-collab #oicr.icgc
  name.state: score-submission-rdpc-collab-qa.state #score-rdpc-collab-qa.state #icgc-argo-collab.state #oicr.icgc

metadata:
  url: https://submission-song.rdpc-qa.cancercollaboratory.org #https://song.rdpc.cancercollaboratory.org #https://virginia.song.icgc.org
  useLegacyMode: false

---

###############################################################################
# Profile - "collaboratory"
###############################################################################

spring:
  profiles: collaboratory

s3:
  endpoint: https://object.cancercollaboratory.org:9080 #https://object.cancercollaboratory.org:9080
  masterEncryptionKeyId:
  accessKey: TO1DRTS4H14HJ388I26R #64M75TSW9OQ0BKDG6EDB
  secretKey: hG1oByzSl0U7SGIiBocNMIdIFLpaMXtmJuCUnRKA #Qdd2c7kUuSWHNYnz49NynQV829waGjPNSw2fYaaZ

metadata:
  url: https://submission-song.rdpc-qa.cancercollaboratory.org #https://song.rdpc.cancercollaboratory.org #https://song.cancercollaboratory.org
  useLegacyMode: false

---

###############################################################################
# Profile - "azure"
###############################################################################

spring:
  profiles: azure

azure:
  endpointProtocol: https
  accountName: argordpcdev #oicricgc
  accountKey: aeVwNiMfJx1p6lBoIqJfOzXDP+YRkPNDdSKR5K/a9NGBUiR4X+M1rzhk+i0p5uMbAVZZ5FG45J/++AStGIgsCQ==

bucket:
  name.object: icgc-argo-dev #data
  name.state: qa.icgc
  policy.upload: write #UploadPolicy
  policy.download: readonly #DownloadPolicy

download:
  partsize: 250000000

---

###############################################################################
# Profile - "prod"
###############################################################################

spring.profiles: prod

s3:
  secured: true

# Metadata server
metadata:
  url: https://submission-song.rdpc-qa.cancercollaboratory.org #https://song.rdpc.cancercollaboratory.org #https://meta.icgc.org

---

###############################################################################
# Profile - "secure"
###############################################################################

spring.profiles: secure

# OAuth authentication server
auth:
  server:
    url: https://ego.dev.argo.cancercollaboratory.org/api/o/check_api_key #https://ego.icgc-argo.org/api/o/check_api_key #https://localhost:8443/oauth/check_token
    tokenName: apiKey #token
    clientId: score-rdpc-collab #resource
    clientSecret: hQI71%7fNrCnHmTcyit* #pass
    scope:
      download:
        system: score.READ #aws.download
        study:
          prefix: PROGRAMDATA-   #aws.
          suffix: .READ #.download
      upload:
        system: score.WRITE #aws.upload
        study:
          prefix: PROGRAMDATA- #aws.
          suffix: .WRITE #.upload
---

###############################################################################
# Profile - "jwt"
###############################################################################

spring:
  profiles: jwt
  profiles.include: secure

auth:
  jwt:
    publicKeyUrl: "https://ego.dev.argo.cancercollaboratory.org/api/oauth/token/public_key" #"https://ego.icgc-argo.org/api/oauth/token/public_key" #"https://localhost:8443/oauth/token/public_key"
---

###############################################################################
# Profile - "dev"
###############################################################################

spring.profiles: dev

s3:
  secured: false
  #endpoint: localhost:9444/s3
  accessKey: AKIAIOSFODNN7EXAMPLE
  secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

# Server
server:

bucket:
  name.object: test.icgc
  name.state: test.icgc

upload:
  clean.enabled: false

---

###############################################################################
# Profile - "benchmark"
###############################################################################

spring.profiles: benchmark

# Server
server:
  ssl:
    key-store-type: JKS

s3:
  secured: false
  # Sinai Center
  endpoint: http://www.cancercollaboratory.org:9081

---

spring:
  profiles:
    active: azure,prod,jwt,secure #,collaboratory,prod,jwt #, secure,amazon

logging.level:
  #  org.springframework: debug
  bio.overture.score.server: info