#!/bin/bash
if [ $DOCKER_REPO == "overture/score" ]; then
	docker build --target client -f $DOCKERFILE_PATH -t $DOCKER_REPO:edge .
else
	docker build --target server -f $DOCKERFILE_PATH -t $DOCKER_REPO:$SOURCE_COMMIT .
fi
