#!/bin/bash
echo "Pushing tag $DOCKER_REPO:$SOURCE_COMMIT"
docker push $DOCKER_REPO:$SOURCE_COMMIT

echo "Tagging image $DOCKER_REPO:$SOURCE_COMMIT with tag $DOCKER_REPO:edge"
docker tag $DOCKER_REPO:$SOURCE_COMMIT $DOCKER_REPO:edge

echo "Pushing tag $DOCKER_REPO:edge"
docker push $DOCKER_REPO:edge

regex="^([0-9]+\.[0-9]+\.[0-9]+)$"
echo "SOURCE_BRANCH=${SOURCE_BRANCH}"
tag=`git describe --tags`
echo "TAG=${tag}"

if [[ ${tag} =~ $regex ]]; then
    version="${BASH_REMATCH[1]}"
    echo "$SOURCE_BRANCH matches to reges: $regex. Tagging and pushing versioned image with ${version}..."

    echo "Tagging image $DOCKER_REPO:$SOURCE_COMMIT with tag $DOCKER_REPO:${version}"
    docker tag $DOCKER_REPO:$SOURCE_COMMIT $DOCKER_REPO:${version}

    echo "Pushing tag $DOCKER_REPO:${version}"
    docker push $DOCKER_REPO:${version}

    echo "Tagging image $DOCKER_REPO:$SOURCE_COMMIT with tag $DOCKER_REPO:latest"
    docker tag $DOCKER_REPO:$SOURCE_COMMIT $DOCKER_REPO:latest

    echo "Pushing tag $DOCKER_REPO:latest"
    docker push $DOCKER_REPO:latest
else
    echo "$SOURCE_BRANCH does not match the regex: $regex. Versioned image not pushed"
fi
