	CREATE TABLE AUDIT_EVENTS (
		EVENT_TS TIMESTAMP, 
		EVENT_DATE DATE AS (TRUNCATE(EVENT_TS)), 
		EVENT_TYPE VARCHAR(10), 
		OBJECT_ID VARCHAR(36), 
		ACCESS_TOKEN VARCHAR(36)
	);
	
	CREATE TABLE USERS (  
		ACCESS_TOKEN VARCHAR(36),
		USER_NAME VARCHAR(256),
		IS_DELETED BOOLEAN
	);

	CREATE INDEX IDX_USERS ON USERS(ACCESS_TOKEN);

	CREATE TABLE DCC_OBJECTS (  
		ID VARCHAR(36),
		FILE_FORMAT VARCHAR(10),
		FILE_NAME VARCHAR(256),
		FILE_SIZE BIGINT
	);

	CREATE INDEX IDX_DCC_OBJECTS ON DCC_OBJECTS(ID);
